version: "3.5"

services:
  frontend:
    restart: always
    env_file:
      - .env
    container_name: frontend

  backend:
    build: ./backend
    restart: always
    env_file:
      - .env
    container_name: backend
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"

  nginx:
    image: event_app_nginx
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - $HOSTPORT:8080
    restart: always
    depends_on:
      - frontend
