version: "3.5"

services:
  frontend:
    build:
      dockerfile: dev.Dockerfile
      context: ./frontend
    volumes:
      - /frontend/node_modules
      - ./frontend:/frontend

  backend:
    volumes:
      - ./backend:/backend

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./database:/data/db

  nginx:
    build:
      context: ./nginx
      args:
        CONFIG_FILE: dev.conf
