version: "3.5"

services:
  frontend:
    build:
      dockerfile: dev.Dockerfile
      context: ./frontend
    volumes:
      - /frontend/node_modules
      - ./frontend:/frontend
    ports:
      - 8080:3000
    stdin_open: true
    tty: true

  backend:
    volumes:
      - ./backend:/backend
    ports:
      - 4000:5000

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./database:/data/db
